shadow-exclude = [ "class_g = 'Firefox' && argb" ];
inactive-opacity = 0.80;
menu :
{
    shadow = false;
};
dropdown_menu :
{
    shadow = false;
};
popup_menu :
{
    shadow = false;
};
utility :
{
    shadow = false;
}