#!/bin/bash
# Install dribblish - Beach-Sunset and fullAppDisplay
cd "$(dirname "$(spicetify -c)")/Themes/Dribbblish"
mkdir -p ../../Extensions
cp dribbblish.js ../../Extensions/.
spicetify config extensions dribbblish.js
spicetify config current_theme Dribbblish color_scheme base
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
spicetify config color_scheme Beach-Sunset
spicetify config extensions fullAppDisplay.js
spicetify apply
